+++
title = "stg-rebase(1)"
+++

stg-rebase(1)
=============

NAME
----
stg-rebase - Move the stack base to another point in history

SYNOPSIS
--------
[verse]
'stg rebase' [OPTIONS] [committish]

DESCRIPTION
-----------

Pop all patches from the current stack, move the stack base to the given new
base and push the patches back.

Merge conflicts may arise when patches are being pushed-back onto the stack. If
this occurs, resolve the conflicts and then continue the rebase with the
following sequence:

    stg add --update
    stg refresh
    stg goto top-patch

Or to skip the conflicting patch:

    stg undo --hard
    stg push next-patch..top-patch


OPTIONS
-------
-i::
--interactive::
    Interactively manipulate patches in editor

-n::
--nopush::
    Do not push back patches after rebasing

-m::
--merged::
    Check for patches that may have been merged upstream.
+
When pushing-back patches, each patch is checked to see if its changes already
exist in the new stack base. If a patch's changes are detected to have been
merged, the patch will still exist in the stack, but become empty after the
rebase operation.

--autostash::
    Automatically create a temporary stash before the operation begins, and
    apply it after the operation completes. This allows a rebase to be
    performed on a dirty work tree. Note however that the final stash
    application may result in non-trivial conflicts.

StGit
-----
Part of the StGit suite - see linkman:stg[1]
