+++
title = "stg-series(1)"
+++

stg-series(1)
=============

NAME
----
stg-series - Display the patch series

SYNOPSIS
--------
[verse]
'stg series' [OPTIONS] [-A] [-U] [-H]
'stg series' [OPTIONS] --all
'stg series' [OPTIONS] --short
'stg series' [OPTIONS] <patch>...

DESCRIPTION
-----------

Show all the patches in the series, or just those in the given range, ordered
from top to bottom.

The applied patches are prefixed with a '+' (except the current patch, which is
prefixed with a '>'), the unapplied patches with a '-', and the hidden patches
with a '!'.

Empty patches are prefixed with a '0'.

OPTIONS
-------
-b <branch>::
--branch=<branch>::
    Use BRANCH instead of current branch

-a::
--all::
    Select all patches, including hidden patches

-s::
--short::
    Select patches around the topmost patch only

-A::
--applied::
    Select the applied patches only

-U::
--unapplied::
    Select the unapplied patches only

-H::
--hidden::
    Select the hidden patches only

-m <branch>::
--missing=<branch>::
    Select patches in <branch> not present in current branch

--author::
    Display author name for each patch

-c::
--count::
    Display the number of selected patches and exit

-i[=<length>]::
--commit-id[=<length>]::
    Display the commit id for each patch.
+
The optional length indicates how many prefix characters of the commit id to
display. The default is "full", which displays the full commit id, but may
alternatively be specified as a positive integer greater than or equal to 4.

-d::
--description::
    Display short description for each patch

--no-description::
    Do not display the patch description

-e::
--empty::
    Before the '+', '>', '-', and '!' prefixes, print a column that contains
    either '0' (for empty patches) or a space (for non-empty patches).

-P::
--no-prefix::
    Do not display the patch status prefix

--showbranch::
    Display the branch name with the listed patches

StGit
-----
Part of the StGit suite - see linkman:stg[1]
